name: Screenshots

on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties        

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Record screenshot tests (Roborazzi)
        id: screenshots-verify
        run: |
          ./gradlew :feature:foryou:recordRoborazziDemoDebug

      - name: Generate md5 hashes
        run: | 
          ls screenshots/
          find screenshots/ -type f -name "*.png" -exec md5sum {} + | awk '{print $1 > $2 ".md5"}' 

      - name: Fail if md5 hashes changed
        id: md5check
        continue-on-error: true
        run: git diff --exit-code --quiet -- screenshots/ && exit 0 || exit 1

      - name: Check out base branch and record screenshots if failed
        if: steps.md5check.outcome == 'failure'
        run: |
          git reset --hard # Remove modified files
          git clean -f -x # Remove untracked files
          git fetch origin ${{ github.base_ref }} --depth 1
          git checkout ${{ github.base_ref }}
          ./gradlew :feature:foryou:recordRoborazziDemoDebug

      - name: Compare screenshots
        if: steps.md5check.outcome == 'failure'
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          ./gradlew :feature:foryou:compareRoborazziDemoDebug

      - name: Upload screenshots to build artifacts
        if: steps.md5check.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/*_compare.png

      - name: Generate the new md5 hashes
        if: steps.md5check.outcome == 'failure'
        run: |
          rm screenshots/*.md5
          find screenshots/ -type f -name "*.png" ! -name "*_compare.png" -exec md5sum {} + | awk '{print $1 > $2 ".md5"}' 
          ls -al screenshots/

      # Runs if previous job failed
      - name: Push new screenshot md5s if failed
        if: steps.md5check.outcome == 'failure'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          ls -al screenshots/
          git add screenshots/*.md5
          git commit -m "ðŸ¤– Updates screenshots"
          git push
